# Generated by Django 4.2.6 on 2023-12-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="missing", verbose_name="실종 동물 사진"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "missing_location",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("register_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Missing_Image",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000, null=True)),
                ("main_img_id", models.IntegerField(default=-1)),
                (
                    "main_img",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("register_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Post",
            },
        ),
        migrations.CreateModel(
            name="PostAlarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_username", models.CharField(max_length=15, null=True)),
                ("register_username", models.CharField(max_length=15, null=True)),
                ("alarm_message", models.CharField(max_length=100)),
                ("content_type", models.IntegerField()),
                ("content_id", models.IntegerField(blank=True, null=True)),
                ("register_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Post_Alarm",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_image",
                        to="animal.animalimage",
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.post"
                    ),
                ),
            ],
            options={
                "db_table": "Post_Image",
            },
        ),
    ]
