# Generated by Django 4.2.6 on 2023-11-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimage",
            old_name="register_data",
            new_name="register_date",
        ),
        migrations.RenameField(
            model_name="postlike",
            old_name="register_data",
            new_name="register_date",
        ),
    ]
