# Generated by Django 4.2.6 on 2023-12-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAlarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_username", models.CharField(max_length=15, null=True)),
                ("register_username", models.CharField(max_length=15, null=True)),
                ("alarm_message", models.CharField(max_length=100)),
                ("content_type", models.IntegerField()),
                ("content_id", models.IntegerField(blank=True, null=True)),
                ("register_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Post_Alarm",
            },
        ),
    ]
