# Generated by Django 4.2.6 on 2023-11-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_register_data_postimage_register_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="main_img",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="main_img_id",
            field=models.IntegerField(default=-1),
        ),
    ]
