# Generated by Django 4.2.6 on 2023-11-10 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_post_main_img_post_main_img_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="missing", verbose_name="실종 동물 사진"
                    ),
                ),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                (
                    "register_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Missing_Image",
            },
        ),
    ]
