# Generated by Django 4.2.6 on 2023-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_postimage_image_id_postimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts", verbose_name="post 사진"
            ),
        ),
    ]
