# Generated by Django 4.2.6 on 2023-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=16, unique=True, verbose_name="별명"),
        ),
    ]
