# Generated by Django 4.2.6 on 2023-11-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="characteristic",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="반려동물 특징"
            ),
        ),
    ]
